# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  app.controller.category_controller:
    class: AppBundle\Controller\CategoryController
    autowire: true

  app.controller.homepage_controller:
    class: AppBundle\Controller\HomepageController
    autowire: true

  app.controller.help_controller:
    class: AppBundle\Controller\HelpController
    autowire: true

  app.controller.product_controller:
    class: AppBundle\Controller\ProductController
    autowire: true

  app.controller.user_controller:
    class: AppBundle\Controller\UserController
    autowire: true

  app.controller.cart_controller:
    class: AppBundle\Controller\CartController
    autowire: true

  app.facade.category_facade:
    class: AppBundle\Facade\CategoryFacade
    autowire: true

  app.facade.product_facade:
    class: AppBundle\Facade\ProductFacade
    autowire: true

  app.facade.user_facade:
    class: AppBundle\Facade\UserFacade
    autowire: true

  app.facade.cart_facade:
    class: AppBundle\Facade\CartFacade
    autowire: true

  app.facade.cart_item_facade:
    class: AppBundle\Facade\CartItemFacade
    autowire: true

  app.repository.address_repository:
    class: AppBundle\Repository\AddressRepository
    factory:   ['@doctrine.orm.default_entity_manager', getRepository]
    arguments: ['AppBundle\Entity\Address']

  app.repository.category_repository:
    class: AppBundle\Repository\CategoryRepository
    factory:   ['@doctrine.orm.default_entity_manager', getRepository]
    arguments: ['AppBundle\Entity\Category']

  app.repository.faq_repository:
    class: AppBundle\Repository\FaqRepository
    factory:   ['@doctrine.orm.default_entity_manager', getRepository]
    arguments: ['AppBundle\Entity\Faq']

  app.repository.product_repository:
    class: AppBundle\Repository\ProductRepository
    factory:   ['@doctrine.orm.default_entity_manager', getRepository]
    arguments: ['AppBundle\Entity\Product']

  app.repository.cart_repository:
    class: AppBundle\Repository\CartRepository
    factory:   ['@doctrine.orm.default_entity_manager', getRepository]
    arguments: ['AppBundle\Entity\Cart']

  app.repository.cart_item_repository:
    class: AppBundle\Repository\CartItemRepository
    factory:   ['@doctrine.orm.default_entity_manager', getRepository]
    arguments: ['AppBundle\Entity\CartItem']

  encoder:
    class: Symfony\Component\Security\Core\Encoder\BCryptPasswordEncoder
    arguments:
      - 13
